### ISSUE TITLE
Multiple reCAPTCHA elements on the authentication screen

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [prplwtf/Nebula#1]
On the login/authentication page, there are two reCAPTCHA elements.

![image](https://github.com/prplwtf/Nebula/assets/102361830/8254ce86-810a-4897-845e-dd71ef0fb127)

I'd imagine intended behavior would be one element, the bottom right one, not the default Pterodactyl one.

**Comment by prplwtf** [comment]
Implemented and released.
