### ISSUE TITLE
Bug with the order

### ISSUE THREAD

**Issue by SaltyAlpaca** [prplwtf/Nebula#100]
It is this where i have set it to left and it is set to the right
![image](https://github.com/user-attachments/assets/bc114ccb-897c-44cd-a1b2-3f8adf1cf6c5)

![image](https://github.com/user-attachments/assets/cec87a91-6e75-4f79-bcdf-432a493e5561)

**Comment by prplwtf** [comment]
This is slightly complicated. The website button alignment is based on the first section (website, status, billing). Social buttons have their alignment inverted.

**Comment by prplwtf** [comment]
I'm going to close this as "not planned" for now. I'm probably going to modify the wording on the alignment options to showcase it based on button type and not left/right.
