### ISSUE TITLE
[Suggestion] Custom color background for announcements within the icon selected

### ISSUE THREAD

**Issue by MrAstro18** [prplwtf/Nebula#32]
For each icons made to use on announcements, it would be useful to set custom color background depending on the case. For example, the warning icon would display a yellow background (or another color of the user's choice)
![image](https://github.com/prplwtf/Nebula/assets/88798450/2d1172fc-097b-4072-a24e-9ba9f9bc6474)

**Comment by prplwtf** [comment]
Duplicate of #24
