### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by medaria** [prplwtf/Nebula#35]
When you install it, you no longer have the "Start, Restart, Stop" icons, the buttons to press are already there and can be pressed, but the icons are missing

http://iwintra.net/uploads/medaria/e9bb1bdb-b9b7-4045-be6d-66fcf1cda8db.jpg
http://iwintra.net/uploads/medaria/a0d42070-4bd4-4d1c-9525-8a39df3c1c58.jpg
http://iwintra.net/uploads/medaria/366f566d-2f4d-404b-99a9-f428b3464580.jpg

http://iwintra.net/uploads/medaria/ae1eb5dd-ec9c-4bcc-bc0a-12f4a3001906.jpg

**Comment by prplwtf** [comment]
Due to some limitations, Nebula has to read the text inside of the power buttons. Due to you changing this text in the form of a panel translation, the button can no longer be found and won't show up.
