### ISSUE TITLE
transitions between navigating designer pages

### ISSUE THREAD

**Issue by prplwtf** [prplwtf/Nebula#39]

**Comment by prplwtf** [comment]
Assigned to @Spoopy2023

**Comment by Spoopy2023** [comment]
https://github.com/prplwtf/NebulaCodebase/commit/4f1ac5ba218f797b4baf22950ffc5d7c38eaccfe

**Comment by Spoopy2023** [comment]
Still wip

**Comment by prplwtf** [comment]
Marked as completed.
