### ISSUE TITLE
Change color of the Server online bars (Menu dashboard)

### ISSUE THREAD

**Issue by Kuveru** [prplwtf/Nebula#42]
![Captura de pantalla 2024-06-07 225547](https://github.com/prplwtf/Nebula/assets/152223676/3ae98cdb-40de-4844-be40-1d290c3939dc)

It would be cool if you can add something to change the colours of more things in the panel, like the online server bar in the dashboard.

**Comment by prplwtf** [comment]
Might be difficult to implement as the colors are (if I remember correctly) defined as split-up RGB values compared to the standard HEX values used by Nebula.

**Comment by prplwtf** [comment]
I've got it working now - will be included in the next release.
![Image](https://github.com/prplwtf/Nebula/assets/103201875/40e83f62-1830-4a22-a292-07d9b15ec2ca)
