### ISSUE TITLE
Middle-click not working on sidebar

### ISSUE THREAD

**Issue by abashelcam** [prplwtf/Nebula#7]
Have to right click and press on "open in new tab" which is annoying.

**Comment by prplwtf** [comment]
This menu has been added as a sort of bandaid fix for middle click not being available.

I have not been able to implement the "middle click" feature you are looking for yet. I doubt there is a performant way to implement this, as I haven't been able to really find a solution for it yet.

**Comment by prplwtf** [comment]
Got a working version of this, just got to tidy some things up. Will be released alongside other features in the next Nebula release.

**Comment by abashelcam** [comment]
Okay, thanks!
