### ISSUE TITLE
"Icon + text" sidebar style

### ISSUE THREAD

**Issue by victorpahuus** [prplwtf/Nebula#9]
I really like Nebula and the design that the theme offers. However, I think there is a lack of an option to make the menu/sidebar a "normal" width sidebar. Unfortunately, right now I don't think the icons themselves are enough to make it user-friendly. There is a need for some menu items with text that also have an icon.

**Comment by prplwtf** [comment]
Got everything working alongside some customizable options. All that's left for this is better mobile optimization.

**Comment by prplwtf** [comment]
Everything's set! Will be pushed in the 1.8 release sometime this week (or even earlier).

**Comment by prplwtf** [comment]
Implemented and released.
